apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: generate-api

resources:
  - namespace.yaml
  - generate-api-config.yaml
  - generate-api-deployment.yaml
  - generate-api-service.yaml
